name: Python CI

on:
  push:
    branches: [main, feat/ci]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configuro Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalo Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Corro tests
        run: |
            pip install pytest pytest-cov
            pytest