name: Python CI

on:
  push:
    branches: [main, feat/ci]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configuro Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalo Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Corro tests
        run: |
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export PORT=${{ secrets.PORT }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            export SECURITY_PASSWORD_SALT=${{ secrets.SECURITY_PASSWORD_SALT }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export USER_SECRET_KEY=${{ secrets.USER_SECRET_KEY }}
            export TESTING=${{ secrets.TESTING }}
            pip install pytest
            pytest